version: "3.7"

services:
  skatespot_web:
    image: skatespot.api:latest
    depends_on:
      - redis_db
      - proxy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - "redis_db"      
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentContainerized
      - ASPNETCORE_URLS=http://+:5000

  redis_db:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"

  proxy:
    image: caddy-proxy:latest    
    ports:
      - "443:443"
    build:
      args:
        ENVIRONMENT: development
      context: ./Proxy
      dockerfile: ./Dockerfile
