namespace SkateSpot.Domain.Common
{
	public enum ErrorCode
	{
		DEFAULT_ERROR,
		ALREADY_EXISTS,
		VOTING_FINISHED,
		DOESNT_EXIST,		
		NOT_OWNED,
		EMAIL_NOT_VERIFIED,
		CANT_DO_THAT,
		IMAGES_MAXED,
		TOO_MANY_IMAGES,
		BAD_INPUT
	}
}